baseurl = "https://anayini.github.io"
DefaultContentLanguage = "en"
title = "b\u00B3"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "building; brewing; boxing"
  logo = "images/avatars/github.jpg"
  favicon = "img/sphere.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Arjun Nayini"
  email = "aanayini@gmail.com"
  github = "anayini"
  twitter = "anayini"
  instagram = "arjunnayini"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
name = "Tags"
url = "tags"
weight = 3
